POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "Kyle",
    "password": "password"
}

###
GET http://localhost:4000/users

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle",
    "password": "password"
}

###

GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5ODAwMjIxOCwiZXhwIjoxNTk4MDAzMTE4fQ.ZDYHvOsdCCmRXmN0Dn0KfnktxVtMYQ7Vhs7KOg8HLts

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5ODAwMDQ3Mn0.KY8TlVbMGlo_vUfx8jJazqMv1cLPPrAmiZfiRiPaa_Y"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5Nzk5OTIxMn0.7vZRWOASBVbjyN9VIY-qG6iJvgGwEQyj0KZAAz-ygW8"
}